@startuml

state Open as "Open\n**Offen**"
state Adressed as "Adressed\n**Adressiert**"
state Evaluated as "Evaluated\n**Bewertet**"
state Decided as "Decided\n**Entschieden**"

[*] --> Open

Open --> Adressed
Adressed --> Evaluated
Evaluated --> Decided

Decided --> [*]

Open : Motivation und Problemstellung sind beschrieben, der Entscheidungsbedarf ist noch nicht adressiert
Adressed : Der Entscheidungsbedarf ist an den Entscheider adressiert, es sind aber noch keine Lösungsalternativen bewertet
Evaluated: Die Lösungsalternativen sind bewertet und eine Empfehlung liegt vor
Decided : Die Entscheidung ist getroffen und kommuniziert

@enduml