@startuml

participant "Plane Reise:\n**mobil.nrw**\n(Mobility Service Provider)" as routing_app
participant "Berechne Routenoptionen:\n**Intermodaler Router**:\n(ZMDZ)" as dz_intermodal_router
participant "Berechne Teilrouten:\n**Intermodaler Router**:\n(ZMDZ)" as dz_router
participant "Berechne Routen zu \nnahegelegenen Startbahnhöfen:\n**Request Broker**:\n(ZMDZ->RRP)" as dz_broker_route_start
participant "Berechne Route von \npotenziellen Zielbahnhöfen:\n**Request Broker**:\n(ZMDZ->RRP)" as dz_broker_route_target
participant "Optimiere Fahrradroute\nGesamtstrecke\n**Fahrradrouting**:\n(RRP NRW)" as  dz_bicycle_router_complete
participant "Berechne ÖPNV-Gesamtroute:\n**Routing Service**:\n(DELFI)" as  delfi_router
participant "Konsolidiere Routen:\n**Assemble Service**:\n(ZMDZ)" as dz_assemble
participant "Konsolidiere Routen:\n**Evaluation Service**:\n(ZMDZ)" as dz_evaluate
participant "Route zu bestimmten Endpunkt\n**Fahrradrouting**:\n(RRP NRW)" as rrp_routing 

note over dz_router: Ermittle potentielle Start- und Zielbahnhöfe\nund Fahrradrouten parallel zur DELFI-Route\n("Prefetching" der potentiellen Fahrradrouten)

routing_app -> dz_intermodal_router : GET /planning-options/\n{ **journey_start** }/{ **journey_target** }?\nmodal=**bike,öpnv,bike+öpnv**
activate routing_app
activate dz_intermodal_router
dz_intermodal_router -> dz_router : GET /planning-parts/\n{ **journey_start** }/{ **journey_target** }?\nmodal=**bike,öpnv,bike+öpnv**
activate dz_router
par
dz_router  ->> dz_broker_route_start : GET routes-to-nearest-poi/\n{ **journey_start** }?\ntags=**railway.halt,railway.stop**\nmodal=**bike**
activate dz_broker_route_start

dz_router  <<-- dz_broker_route_start: Response: { **optimized_bicycle_start_route** }
deactivate dz_broker_route_start

dz_router  ->> dz_broker_route_target :  : GET route-from-nearest-poi/\n{ **journey_target** }?\ntags=**railway.halt,railway.stop**\nmodal=**bike**
activate dz_broker_route_target

dz_router  <<-- dz_broker_route_target: Response: { **optimized_bicycle_target_route** }
deactivate dz_broker_route_target

dz_router  ->> dz_bicycle_router_complete : GET route/\n{ **journey_start** }/{ **journey_target** }\n?modal=**bike**
activate dz_bicycle_router_complete
dz_router  <<-- dz_bicycle_router_complete: Response: { **optimized_bicycle_complete_route** }
deactivate dz_bicycle_router_complete
dz_router  ->> delfi_router : GET route/\n{ **journey_start** }/{ **journey_target** }?modal=**bike,öpnv,bike+öpnv**
activate delfi_router
dz_router  <<-- delfi_router: Response: { **delfi_route** }
deactivate delfi_router
end

dz_intermodal_router <- dz_router : Response: { **bike_optimized_planning_parts **}
deactivate  dz_router

dz_intermodal_router  -> dz_assemble : GET consolidated-routes/\n{ **öpnv-routes**,\n **bicycle routes** }
activate dz_assemble
dz_assemble -> dz_evaluate : GET all öpnv-routes with bicycle route
activate dz_evaluate
opt
dz_evaluate -> rrp_routing : GET route to station\n{ ** missing station ** } 
activate rrp_routing
dz_evaluate <- rrp_routing: Response: { **route to missing station** }
deactivate rrp_routing
end
dz_assemble <- dz_evaluate
deactivate dz_evaluate
dz_intermodal_router <- dz_assemble : Response: { ** combined routes ** }
deactivate dz_assemble
dz_intermodal_router  -> dz_intermodal_router: Transform results
dz_intermodal_router --> routing_app: Response: { **bike_optimized_delfi_options** }
deactivate dz_intermodal_router
deactivate routing_app

note right dz_broker_route_start: "PostGis - DB"

@enduml
