@startuml
class Position << TOMP-API NRW - Extension >>

note top of Position : Positon objects have "AdditionalProperties=true" within the TOMP-API Spec, i.e. they can be extended without breaking the contract

Leg .. Position

class Leg

@enduml
